In [47]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv('Downloads/winequality-red.csv')

In [49]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
#df=df[(df['fixed acidity']>4) & (df['fixed acidity']) & (df['volatile acidity']>0) & (df['volatile acidity']<1.25) & (df['citric acid']>0) & (df['citric acid']<0.8) & (df['residual sugar']>1) & (df['residual sugar']<8) & (df['chlorides']>0) & (df['chlorides']<0.2) & (df['free sulfur dioxide']>0) & (df['free sulfur dioxide']<60)]

In [5]:
#df=df[(df['total sulfur dioxide']>0) & (df['total sulfur dioxide']<175) & (df['pH']>2.8) & (df['pH']<3.8) & (df['sulphates']>0.25) & (df['sulphates']<1.25) & (df['alcohol']>9) & (df['alcohol']<14)]

In [50]:
for i in df.index:
    if df['quality'][i]>=7:
        df['quality'][i]='good'
    else:
        df['quality'][i]='bad'

D:\conda\anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
D:\conda\anaconda\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
D:\conda\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [51]:
df['quality']

0        bad
1        bad
2        bad
3        bad
4        bad
5        bad
6        bad
7       good
8       good
9        bad
10       bad
11       bad
12       bad
13       bad
14       bad
15       bad
16      good
17       bad
18       bad
19       bad
20       bad
21       bad
22       bad
23       bad
24       bad
25       bad
26       bad
27       bad
28       bad
29       bad
        ... 
1569     bad
1570     bad
1571     bad
1572     bad
1573     bad
1574     bad
1575     bad
1576     bad
1577     bad
1578     bad
1579     bad
1580     bad
1581     bad
1582     bad
1583     bad
1584    good
1585     bad
1586     bad
1587     bad
1588     bad
1589     bad
1590     bad
1591     bad
1592     bad
1593     bad
1594     bad
1595     bad
1596     bad
1597     bad
1598     bad
Name: quality, Length: 1599, dtype: object

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le=LabelEncoder()
l=le.fit_transform(df['quality'])

In [54]:
l

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
df['quality']=l

In [56]:
X = df.drop('quality',axis=1)

In [57]:
y = df['quality']

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
sc = StandardScaler()

In [61]:
X = sc.fit_transform(X)

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
rfc = RandomForestClassifier(n_estimators=17,random_state=0)

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [90]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=17, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [91]:
y_pred = rfc.predict(X_test)

In [92]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,r2_score

In [93]:
print(confusion_matrix(y_test,y_pred))

[[282   8]
 [ 10  20]]


In [94]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.97      0.97      0.97       290
          1       0.71      0.67      0.69        30

avg / total       0.94      0.94      0.94       320



In [95]:
l=[]
for i in range(2,200):
    rfc = RandomForestClassifier(n_estimators=i,random_state=0)
    rfc.fit(X_train,y_train)
    y_pred = rfc.predict(X_test)
    l=l+[accuracy_score(y_test,y_pred)]
print(max(l),l.index(max(l)))

0.94375 15


In [36]:
from sklearn.ensemble import RandomForestRegressor

In [77]:
rfr = RandomForestRegressor(n_estimators=40,random_state=0)
rfr.fit(X_train,y_train)
rfr_pred = rfr.predict(X_test)

In [78]:
acc=accuracy_score(y_test, y_pred)
print("accuracy: ",acc*100,"%" )

accuracy:  93.125 %


In [72]:
rfr_pred

array([0.   , 0.   , 0.025, 0.075, 0.   , 0.45 , 0.   , 0.5  , 0.875,
       0.125, 0.   , 0.05 , 0.275, 0.   , 0.775, 0.125, 0.1  , 0.3  ,
       0.15 , 0.175, 0.   , 0.15 , 0.   , 0.   , 0.825, 0.25 , 0.025,
       0.775, 0.65 , 0.025, 0.225, 0.075, 0.375, 0.025, 0.225, 0.025,
       0.075, 0.   , 0.   , 0.1  , 0.7  , 0.   , 0.   , 0.   , 0.625,
       0.05 , 0.   , 0.675, 0.525, 0.05 , 0.   , 0.025, 0.   , 0.1  ,
       0.075, 0.725, 0.   , 0.625, 0.   , 0.125, 0.075, 0.25 , 0.075,
       0.   , 0.125, 0.   , 0.   , 0.1  , 0.   , 0.   , 0.55 , 0.425,
       0.   , 0.   , 0.   , 0.05 , 0.   , 0.725, 0.   , 0.275, 0.   ,
       0.125, 0.   , 0.   , 0.625, 0.025, 0.   , 0.1  , 0.025, 0.175,
       0.625, 0.85 , 0.   , 0.525, 0.   , 0.   , 0.   , 0.275, 0.925,
       0.075, 0.   , 0.   , 0.525, 0.025, 0.   , 0.025, 0.325, 0.75 ,
       0.825, 0.   , 0.725, 0.975, 0.025, 0.05 , 0.075, 0.025, 0.   ,
       0.   , 0.   , 0.   , 0.175, 0.7  , 0.5  , 0.65 , 0.65 , 0.725,
       0.25 , 0.05 ,

In [73]:
l=[]
for i in range(2,100):
    rfr = RandomForestRegressor(n_estimators=i,random_state=0)
    rfr.fit(X_train,y_train)
    rfr_pred = rfr.predict(X_test)
    l=l+[accuracy_score(y_test, y_pred)]
print(max(l),l.index(max(l)))

0.93125 0
